Layout/AlignHash:
  EnforcedColonStyle:
    - key
    - table

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

# Variable

Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  Max: 29

Metrics/ClassLength:
  Max: 139

Metrics/MethodLength:
  Max: 20

Metrics/LineLength:
  Max: 160
